# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Arma_colSums <- function(x) {
    .Call(`_phisweepr_Arma_colSums`, x)
}

Sugar_colSums <- function(x) {
    .Call(`_phisweepr_Sugar_colSums`, x)
}

Cpp_colSums <- function(x) {
    .Call(`_phisweepr_Cpp_colSums`, x)
}

Arma_colSums_spM <- function(x) {
    .Call(`_phisweepr_Arma_colSums_spM`, x)
}

